import { ServiceItem, ServicesSectionConfig } from '@/types/services';
import { ROUTES } from './routes';

export const defaultServices: ServiceItem[] = [
  {
    id: 'weight-loss',
    title: 'Weight Loss',
    subtitle: '(GLP-1)',
    href: `${ROUTES.SERVICES || '/services'}/weight-loss`,
    imageSrc: '/assets/images/weight loss.jpg',
    imageAlt: 'Weight Loss (GLP-1)',
  },
  {
    id: 'mens-health',
    title: "Men's Health",
    subtitle: '(TRT)',
    href: `${ROUTES.SERVICES || '/services'}/mens-health`,
    imageSrc: "/assets/images/Men's Health.jpg",
    imageAlt: "Men's Health (TRT)",
    iconName: 'male',
    iconColor: 'text-[#2563EB]',
  },
  {
    id: 'womens-health',
    title: "Women's Health",
    subtitle: '(HRT)',
    href: `${ROUTES.SERVICES || '/services'}/womens-health`,
    imageSrc: "/assets/images/women's Health.jpg",
    imageAlt: "Women's Health (HRT)",
    iconName: 'female',
    iconColor: 'text-[#9333EA]',
  },
  {
    id: 'peptides-longevity',
    title: 'Peptides & Longevity',
    subtitle: 'Cellular Wellness',
    href: `${ROUTES.SERVICES || '/services'}/peptides-longevity`,
    imageSrc: '/assets/images/Peptides & Longevity.jpg',
    imageAlt: 'Peptides & Longevity Cellular Wellness',
    iconName: 'flask',
    iconColor: 'text-[#059669]',
  },
  {
    id: 'direct-primary-care',
    title: 'Direct Primary Care',
    subtitle: '(Membership)',
    href: `${ROUTES.SERVICES || '/services'}/direct-primary-care`,
    imageSrc: '/assets/images/Direct Primary Care.jpg',
    imageAlt: 'Direct Primary Care (Membership)',
    iconName: 'stethoscope',
    iconColor: 'text-[#16A34A]',
  },
  {
    id: 'urgent-care',
    title: 'Urgent Care',
    subtitle: '(On-Demand)',
    href: `${ROUTES.SERVICES || '/services'}/urgent-care`,
    imageSrc: '/assets/images/Urgent care.jpg',
    imageAlt: 'Urgent Care (On-Demand)',
    iconName: 'zap',
    iconColor: 'text-[#0284C7]',
  },
  {
    id: 'dermatology',
    title: 'Dermatology',
    subtitle: 'Skin, Hair & Nails',
    href: `${ROUTES.SERVICES || '/services'}/dermatology`,
    imageSrc: '/assets/images/Dermatology.jpg',
    imageAlt: 'Dermatology Skin, Hair & Nails',
    iconName: 'moon',
    iconColor: 'text-[#D97706]',
  },
  {
    id: 'mental-health',
    title: 'Mental Health',
    subtitle: '(Biblical Christian-Based)',
    href: `${ROUTES.SERVICES || '/services'}/mental-health`,
    imageSrc: '/assets/images/mental Health.jpg',
    imageAlt: 'Mental Health (Biblical Christian-Based)',
    iconName: 'lightbulb',
    iconColor: 'text-[#6366F1]',
  },
  {
    id: 'prayer-support',
    title: 'Prayer & Support',
    subtitle: '(Always Free)',
    href: `${ROUTES.SERVICES || '/services'}/prayer-support`,
    imageSrc: '/assets/images/prayer & Support.jpg',
    imageAlt: 'Prayer & Support (Always Free)',
    iconName: 'heart',
    iconColor: 'text-[#B45309]',
  },
  {
    id: 'not-sure',
    title: "I'm Not Sure",
    subtitle: 'Help Me Choose',
    href: `${ROUTES.SERVICES || '/services'}/help-me-choose`,
    imageSrc: "/assets/images/i'm not sure.jpg",
    imageAlt: "I'm Not Sure - Help Me Choose",
    iconName: 'compass',
    iconColor: 'text-[#475569]',
  },
];

export const defaultServicesSectionConfig: ServicesSectionConfig = {
  headline: 'What can we help you with today?',
  subheadline: 'Choose a care option to get started. It only takes a few minutes.',
  viewAllLink: {
    label: 'View All Services',
    href: ROUTES.SERVICES || '/services',
  },
  services: defaultServices,
};
